
spring:
  datasource:
    url: jdbc:mysql://192.168.18.10:3306/leaf_pro?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: MAKINGTAN
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        config:
          enabled: false
        commons-log:
          enabled: true
        slf4j:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000
        wall:
          enabled: true
      initial-size: 3
      max-active: 30
      max-open-prepared-statements: 30
      max-wait: 12000
      min-evictable-idle-time-millis: 30000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
      web-stat-filter:
        enabled: false
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: true
        url-pattern: /*

#开发时启用，打印具体sql执行信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl